### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by chunhualiao** [tristanvdb/rCompile#1]
I have installed the requests module (sudo pip install requests) but still is getting the following error if I run the client on a Mac OS machine: 

rComp gcc test.c -o test.o
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/liao6/workspace/rCompile.git/modules/rCompile/__main__.py", line 7, in <module>
    import rCompile.client
  File "/Users/liao6/workspace/rCompile.git/modules/rCompile/client.py", line 6, in <module>
    import requests
ImportError: No module named requests

**Comment by tristanvdb** [comment]
you need to install the request package for the client:
> pip install request

**Comment by chunhualiao** [comment]
the following command solved the problem: 
export PYTHONPATH=/usr/local/lib/python2.7/site-packages
